FROM ubuntu:22.04

# Avoid prompts during installation
ENV DEBIAN_FRONTEND=noninteractive

# Install dependencies

# Install dependencies
RUN apt-get update && apt-get install -y \
    curl \
    git \
    unzip \
    xz-utils \
    zip \
    libglu1-mesa \
    python3 \
    && rm -rf /var/lib/apt/lists/*


# Install Flutter
RUN git clone https://github.com/flutter/flutter.git /flutter
ENV PATH="/flutter/bin:${PATH}"

# Pre-download Flutter SDK
RUN flutter doctor

# Enable web support
RUN flutter channel stable && \
    flutter upgrade && \
    flutter config --enable-web

WORKDIR /app


EXPOSE 8080

CMD ["python3", "-m", "http.server", "8080", "--directory", "/app/build/web"]